version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    # env_file:
    # - .env
    # some of this config will need more consideration
    links:
     - db
  db:
    image: "redis:alpine"
    ports:
     - "6379:6379"