version: '3'
services:
  proxy:
    build: .
    container_name: proxy
    ports:
    - "8080:8080"
    environment:
      REDIS_PW: "" # Ideally, this would be configured with a secure secrets store like Vault or Conjur
      DB_VALUE: 0
    links:
     - redis
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
    - "6379:6379"