version: '2'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    environment:
      REDIS_URL: redis:6379
      REDIS_PW: "" # Ideally, this would be configured with a secure secrets store like Vault or Conjur
      DB_VALUE: 0
    links:
     - redis
  redis:
    image: "redis:alpine"